### ISSUE TITLE
Videostream undecodable by some h264 decoders

### ISSUE THREAD

**Issue by BotCyborg** [JonesChi/CastScreen#2]
Video stream was unplayable using omxh264dec on a raspberry pi. Issue seems to be with missing
H264 parameter sets.
Commenting out
`if ((mVideoBufferInfo.flags & MediaCodec.BUFFER_FLAG_CODEC_CONFIG) != 0) {
                    mVideoBufferInfo.size = 0;
                }`
in CastService.java solves the problem.
See this answer: http://stackoverflow.com/a/26684736/4683709

**Comment by JonesChi** [comment]
Hi,
Could you create a pull request for this issue and I will merge it, thanks.

**Comment by BotCyborg** [comment]
Sure I'll do that asap.
Thanks for sharing this awesome project.
